/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableCellRenderer;
import MODEL.Genero;
import DAO.GeneroDAO;
import java.awt.Color;

/**
 *
 * @author alan
 */
public class GeneroDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    /*public GeneroDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
     try {
            loadRecords();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }
    */
    
    public GeneroDialog() {
        //super(modal);
     initComponents();
     try {
            loadRecords();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelGenero = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabelGeneroDesc = new javax.swing.JLabel();
        txtGeneroDesc = new java.awt.TextField();
        jLabelGeneroNome = new javax.swing.JLabel();
        txtGeneroNome = new java.awt.TextField();
        btnNovoGenero = new javax.swing.JButton();
        btnSalvarGenero = new javax.swing.JButton();
        btnRemoverGenero = new javax.swing.JButton();
        btnCancelarGenero = new javax.swing.JButton();
        btnFecharGenero = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableGenero = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PainelGenero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(254, 254, 254));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "REGISTRO DE GENERO"));
        jPanel10.setToolTipText("");
        jPanel10.setAlignmentX(0.2F);
        jPanel10.setAlignmentY(0.7F);
        jPanel10.setName("Pais_Tab_Panel"); // NOI18N
        jPanel10.setRequestFocusEnabled(false);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelGeneroDesc.setText("Descriçao:");
        jLabelGeneroDesc.setAlignmentX(1.0F);
        jPanel10.add(jLabelGeneroDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, 20));

        txtGeneroDesc.setBackground(java.awt.SystemColor.activeCaptionBorder);
        txtGeneroDesc.setEnabled(false);
        txtGeneroDesc.setName("txtNome"); // NOI18N
        txtGeneroDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGeneroDescKeyTyped(evt);
            }
        });
        jPanel10.add(txtGeneroDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 470, 50));

        jLabelGeneroNome.setText("Nome do Genero:");
        jLabelGeneroNome.setAlignmentX(1.0F);
        jPanel10.add(jLabelGeneroNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 20));

        txtGeneroNome.setBackground(java.awt.SystemColor.activeCaptionBorder);
        txtGeneroNome.setEnabled(false);
        txtGeneroNome.setName("txtNome"); // NOI18N
        txtGeneroNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGeneroNomeKeyTyped(evt);
            }
        });
        jPanel10.add(txtGeneroNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 230, 20));

        PainelGenero.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 630, 110));

        btnNovoGenero.setText("Novo");
        btnNovoGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoGeneroActionPerformed(evt);
            }
        });
        PainelGenero.add(btnNovoGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 70, -1));

        btnSalvarGenero.setText("Salvar");
        btnSalvarGenero.setActionCommand("btnAlterar");
        btnSalvarGenero.setPreferredSize(new java.awt.Dimension(90, 29));
        btnSalvarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarGeneroActionPerformed(evt);
            }
        });
        PainelGenero.add(btnSalvarGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 100, 30));

        btnRemoverGenero.setText("Remover");
        btnRemoverGenero.setActionCommand("btnRemover");
        btnRemoverGenero.setEnabled(false);
        btnRemoverGenero.setPreferredSize(new java.awt.Dimension(90, 29));
        btnRemoverGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverGeneroActionPerformed(evt);
            }
        });
        PainelGenero.add(btnRemoverGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 100, 30));

        btnCancelarGenero.setText("Cancelar");
        btnCancelarGenero.setActionCommand("btnImprimir");
        btnCancelarGenero.setEnabled(false);
        btnCancelarGenero.setPreferredSize(new java.awt.Dimension(90, 29));
        btnCancelarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarGeneroActionPerformed(evt);
            }
        });
        PainelGenero.add(btnCancelarGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 100, 30));

        btnFecharGenero.setText("Fechar");
        btnFecharGenero.setActionCommand("btnFechar");
        btnFecharGenero.setPreferredSize(new java.awt.Dimension(90, 29));
        btnFecharGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharGeneroActionPerformed(evt);
            }
        });
        PainelGenero.add(btnFecharGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 100, 30));

        JTableGenero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTableGenero.setName(""); // NOI18N
        jScrollPane1.setViewportView(JTableGenero);

        PainelGenero.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 610, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PainelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PainelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarGeneroActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja salvar esse registro?", "Confirmação?", JOptionPane.YES_NO_OPTION);

        if (dialogResult == JOptionPane.YES_OPTION) {
            try {
                if (addRecord == true) {
                    addNew();
                } else {
                    updateRecord();
                }
                addRecord = false;
                
                txtGeneroDesc.setEnabled(false);
                txtGeneroNome.setEnabled(false);
                
                txtGeneroDesc.setBackground(Color.gray);
                txtGeneroNome.setBackground(Color.gray);
                
                enableButtons(true, false, false, false);
                
                loadRecords();
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnSalvarGeneroActionPerformed

 
    private void btnRemoverGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverGeneroActionPerformed
        if (!txtGeneroNome.getText().isEmpty()) {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja excluir esse registro?", "Confirmação?", JOptionPane.YES_NO_OPTION);

            if (dialogResult == JOptionPane.YES_OPTION) {
                try {
                    deleteRecord();
                    loadRecords();
                    clearInputBoxes();
                    enableButtons(true, false, false, false);
                    
                    txtGeneroNome.setEnabled(false);
                    txtGeneroNome.setBackground(Color.gray);
                    
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnRemoverGeneroActionPerformed

    private void btnCancelarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarGeneroActionPerformed
        clearInputBoxes();
        enableButtons(true, false, false, false);
        addRecord = false;
        
        txtGeneroDesc.setEnabled(false);
        txtGeneroNome.setEnabled(false);
        
        txtGeneroDesc.setBackground(Color.gray);
        txtGeneroNome.setBackground(Color.gray);
    }//GEN-LAST:event_btnCancelarGeneroActionPerformed

    private void btnFecharGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharGeneroActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharGeneroActionPerformed

    private void btnNovoGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoGeneroActionPerformed
        addRecord = true;
    
        clearInputBoxes();
        
        txtGeneroDesc.setEnabled(true);
        txtGeneroNome.setEnabled(true);
        
        txtGeneroDesc.setBackground(Color.white);
        txtGeneroNome.setBackground(Color.white);
        
        enableButtons(false, true, true, false);
        
        txtGeneroNome.requestFocus();
    }//GEN-LAST:event_btnNovoGeneroActionPerformed

    private void txtGeneroNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGeneroNomeKeyTyped
       if (txtGeneroNome.getText().length() >= 20 ) // limit textfield to 20 characters
            evt.consume();  
    }//GEN-LAST:event_txtGeneroNomeKeyTyped

    private void txtGeneroDescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGeneroDescKeyTyped
       if (txtGeneroDesc.getText().length() >= 200 ) // limit textfield to 3 characters
            evt.consume();  
    }//GEN-LAST:event_txtGeneroDescKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneroDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneroDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneroDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneroDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GeneroDialog dialog = new GeneroDialog();//new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    boolean addRecord = false;

    private void clearInputBoxes() {
        txtGeneroNome.setText("");
        txtGeneroDesc.setText("");
    }
    
    private void addNew() throws SQLException {
        Genero g = new Genero();
        g.setIdGenero(txtGeneroNome.getText());
        g.setDescricao(txtGeneroDesc.getText());
        GeneroDAO dao = new GeneroDAO();
        dao.insert(g);
    }

    private void updateRecord() throws SQLException {
        Genero g = new Genero();
        g.setIdGenero(txtGeneroNome.getText());
        g.setDescricao(txtGeneroDesc.getText());
        GeneroDAO dao = new GeneroDAO();
        dao.update(g);
    }

    private void deleteRecord() throws SQLException {
        GeneroDAO dao = new GeneroDAO();
        
        dao.remove(txtGeneroNome.getText());
    }
    
    private void loadRecords() throws SQLException {
        String sql = "SELECT idGenero, Descricao FROM Filme.Genero ORDER BY idGenero";
        ResultSetTableModel tableModel = new ResultSetTableModel(sql);
        JTableGenero.setModel(tableModel);
        
        JTableGenero.getColumnModel().getColumn(0).setWidth(50);
        JTableGenero.getColumnModel().getColumn(0).setMinWidth(50);
        //JTableGenero.getColumnModel().getColumn(0).setMaxWidth(50);
        
        JTableGenero.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            try {
                if (JTableGenero.getSelectedRow() >= 0) {
                    Object nome = JTableGenero.getValueAt(JTableGenero.getSelectedRow(), 0);
                    Object desc = JTableGenero.getValueAt(JTableGenero.getSelectedRow(), 1);
                    //Object d = JTableGenero.getValueAt(JTableGenero.getSelectedRow(), 2);

                    txtGeneroNome.setText(nome.toString());
                    txtGeneroDesc.setText(desc.toString());
                    
                    
                    
                    txtGeneroNome.setEnabled(true);
                    txtGeneroDesc.setEnabled(true);//teste
                    
                    txtGeneroDesc.setBackground(Color.white);
                    txtGeneroNome.setBackground(Color.white);// teste
                    
                    enableButtons(false, true, true, true);
                }
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        });
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.LEFT);
        JTableGenero.getColumnModel().getColumn(0).setCellRenderer(rightRenderer);
    }
    
     public void enableButtons(boolean novo, boolean salvar, boolean cancelar, boolean remover){
        btnNovoGenero.setEnabled(novo);
        btnSalvarGenero.setEnabled(salvar);
        btnCancelarGenero.setEnabled(cancelar);
        btnRemoverGenero.setEnabled(remover);
    
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableGenero;
    private javax.swing.JPanel PainelGenero;
    private javax.swing.JButton btnCancelarGenero;
    private javax.swing.JButton btnFecharGenero;
    private javax.swing.JButton btnNovoGenero;
    private javax.swing.JButton btnRemoverGenero;
    private javax.swing.JButton btnSalvarGenero;
    private javax.swing.JLabel jLabelGeneroDesc;
    private javax.swing.JLabel jLabelGeneroNome;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.TextField txtGeneroDesc;
    private java.awt.TextField txtGeneroNome;
    // End of variables declaration//GEN-END:variables
}
