/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.sql.SQLException;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableCellRenderer;
import DAO.GeneroDAO;
import javax.swing.JOptionPane;
import MODEL.Genero;

/**
 *
 * @author alan
 */
public class telaGenero extends javax.swing.JPanel implements java.beans.Customizer {
    
    public telaGenero(java.awt.LayoutManager parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            loadRecords();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }
    
    private Object bean;

    /**
     * Creates new customizer 
     */
    public telaGenero() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog = new javax.swing.JDialog();
        PainelGenero = new javax.swing.JPanel();
        try {
            jScrollPane11 =(javax.swing.JScrollPane)java.beans.Beans.instantiate(getClass().getClassLoader(), "UI.NewCustomizer_jScrollPane1");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        JTableGenero = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabelGeneroDesc = new javax.swing.JLabel();
        txtGeneroDesc = new java.awt.TextField();
        jLabelGeneroNome = new javax.swing.JLabel();
        txtGeneroNome = new java.awt.TextField();
        btnNovoGenero = new javax.swing.JButton();
        btnSalvarGenero = new javax.swing.JButton();
        btnRemoverGenero = new javax.swing.JButton();
        btnCancelarGenero = new javax.swing.JButton();
        btnFecharGenero = new javax.swing.JButton();

        jDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog.setTitle("GENERO");
        jDialog.setBounds(new java.awt.Rectangle(0, 15, 0, 0));
        jDialog.setMinimumSize(new java.awt.Dimension(500, 430));
        jDialog.setPreferredSize(new java.awt.Dimension(500, 430));
        jDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelGenero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTableGenero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Descricao"
            }
        ));
        jScrollPane11.setViewportView(JTableGenero);

        PainelGenero.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 270));

        jPanel10.setBackground(new java.awt.Color(254, 254, 254));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "REGISTRO DE GENERO"));
        jPanel10.setToolTipText("");
        jPanel10.setAlignmentX(0.2F);
        jPanel10.setAlignmentY(0.7F);
        jPanel10.setName("Pais_Tab_Panel"); // NOI18N
        jPanel10.setRequestFocusEnabled(false);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelGeneroDesc.setText("Descriçao:");
        jLabelGeneroDesc.setAlignmentX(1.0F);
        jPanel10.add(jLabelGeneroDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, 20));

        txtGeneroDesc.setName("txtNome"); // NOI18N
        txtGeneroDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneroDescActionPerformed(evt);
            }
        });
        jPanel10.add(txtGeneroDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 470, 50));

        jLabelGeneroNome.setText("Nome do Genero:");
        jLabelGeneroNome.setAlignmentX(1.0F);
        jPanel10.add(jLabelGeneroNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 20));

        txtGeneroNome.setName("txtNome"); // NOI18N
        txtGeneroNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneroNomeActionPerformed(evt);
            }
        });
        jPanel10.add(txtGeneroNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 230, 20));

        PainelGenero.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 630, 110));

        btnNovoGenero.setText("Novo");
        PainelGenero.add(btnNovoGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        btnSalvarGenero.setText("Salvar");
        btnSalvarGenero.setActionCommand("btnAlterar");
        btnSalvarGenero.setEnabled(false);
        btnSalvarGenero.setPreferredSize(new java.awt.Dimension(90, 29));
        btnSalvarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarGeneroActionPerformed(evt);
            }
        });
        PainelGenero.add(btnSalvarGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 100, 30));

        btnRemoverGenero.setText("Remover");
        btnRemoverGenero.setActionCommand("btnRemover");
        btnRemoverGenero.setEnabled(false);
        btnRemoverGenero.setPreferredSize(new java.awt.Dimension(90, 29));
        btnRemoverGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverGeneroActionPerformed(evt);
            }
        });
        PainelGenero.add(btnRemoverGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 100, 30));

        btnCancelarGenero.setText("Cancelar");
        btnCancelarGenero.setActionCommand("btnImprimir");
        btnCancelarGenero.setEnabled(false);
        btnCancelarGenero.setPreferredSize(new java.awt.Dimension(90, 29));
        btnCancelarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarGeneroActionPerformed(evt);
            }
        });
        PainelGenero.add(btnCancelarGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 100, 30));

        btnFecharGenero.setText("Fechar");
        btnFecharGenero.setActionCommand("btnFechar");
        btnFecharGenero.setPreferredSize(new java.awt.Dimension(90, 29));
        btnFecharGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharGeneroActionPerformed(evt);
            }
        });
        PainelGenero.add(btnFecharGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 100, 30));

        jDialog.getContentPane().add(PainelGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 13, 648, 430));

        setDoubleBuffered(false);
        setEnabled(false);
        setFocusable(false);
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);
        getAccessibleContext().setAccessibleName("gs");
        getAccessibleContext().setAccessibleDescription("sdf");
        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFecharGeneroActionPerformed

    private void btnCancelarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarGeneroActionPerformed

    private void btnRemoverGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoverGeneroActionPerformed

    private void btnSalvarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarGeneroActionPerformed

    private void txtGeneroNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroNomeActionPerformed

    private void txtGeneroDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroDescActionPerformed

    private void loadRecords() throws SQLException {
        String sql = "SELECT idGenero, Descricao, FROM Genero ORDER BY idGenero";
        ResultSetTableModel tableModel = new ResultSetTableModel(sql);
        JTableGenero.setModel(tableModel);
        
        JTableGenero.getColumnModel().getColumn(0).setWidth(50);
        JTableGenero.getColumnModel().getColumn(0).setMinWidth(50);
        //JTableGenero.getColumnModel().getColumn(0).setMaxWidth(50);
        
        JTableGenero.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            try {
                if (JTableGenero.getSelectedRow() >= 0) {
                    Object nome = JTableGenero.getValueAt(JTableGenero.getSelectedRow(), 0);
                    Object desc = JTableGenero.getValueAt(JTableGenero.getSelectedRow(), 1);
                    //Object d = JTableGenero.getValueAt(JTableGenero.getSelectedRow(), 2);

                    txtGeneroNome.setText(nome.toString());
                    txtGeneroDesc.setText(desc.toString());
                    
                    
                    
                    txtGeneroNome.setEnabled(true);
                    enableButtons(false, true, true, true);
                }
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        });
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.LEFT);
        JTableGenero.getColumnModel().getColumn(0).setCellRenderer(rightRenderer);
    }
    
     public void enableButtons(boolean novo, boolean salvar, boolean cancelar, boolean remover){
        btnNovoGenero.setEnabled(novo);
        btnSalvarGenero.setEnabled(salvar);
        btnCancelarGenero.setEnabled(cancelar);
        btnRemoverGenero.setEnabled(remover);
    
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableGenero;
    private javax.swing.JPanel PainelGenero;
    private javax.swing.JButton btnCancelarGenero;
    private javax.swing.JButton btnFecharGenero;
    private javax.swing.JButton btnNovoGenero;
    private javax.swing.JButton btnRemoverGenero;
    private javax.swing.JButton btnSalvarGenero;
    private javax.swing.JDialog jDialog;
    private javax.swing.JLabel jLabelGeneroDesc;
    private javax.swing.JLabel jLabelGeneroNome;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane11;
    private java.awt.TextField txtGeneroDesc;
    private java.awt.TextField txtGeneroNome;
    // End of variables declaration//GEN-END:variables
}
