/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableCellRenderer;
import MODEL.Pais;
import MODEL.Diretor;
import DAO.PaisDAO;
import DAO.DiretorDAO;
import java.awt.Color;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author alan
 */
public class DiretorDialog extends javax.swing.JDialog {
    SimpleDateFormat formatter = new SimpleDateFormat("yyyy/MM/dd");

    /**
     * Creates new form NewJDialog
     */
    /*public GeneroDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
     try {
            loadRecords();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }
    */
    
    public DiretorDialog() {
        //super(modal);
     initComponents();
     try {
            loadRecords();
            fillCBBPais();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelGenero = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabelDiretorNome = new javax.swing.JLabel();
        txtDiretorNome = new java.awt.TextField();
        jLabelDiretorData = new javax.swing.JLabel();
        txtDiretorData = new javax.swing.JFormattedTextField();
        cbbPais = new javax.swing.JComboBox<>();
        jLabelDiretorPais = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnNovoDiretor = new javax.swing.JButton();
        btnSalvarDiretor = new javax.swing.JButton();
        btnRemoverDiretor = new javax.swing.JButton();
        btnCancelarDiretor = new javax.swing.JButton();
        btnFecharDiretor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableDiretor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PainelGenero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(254, 254, 254));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "REGISTRO DE DIRETORES"));
        jPanel10.setToolTipText("");
        jPanel10.setAlignmentX(0.2F);
        jPanel10.setAlignmentY(0.7F);
        jPanel10.setName("Pais_Tab_Panel"); // NOI18N
        jPanel10.setRequestFocusEnabled(false);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDiretorNome.setText("Nome:");
        jLabelDiretorNome.setAlignmentX(1.0F);
        jPanel10.add(jLabelDiretorNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 20));

        txtDiretorNome.setBackground(java.awt.SystemColor.activeCaptionBorder);
        txtDiretorNome.setEnabled(false);
        txtDiretorNome.setName("txtNome"); // NOI18N
        txtDiretorNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiretorNomeKeyTyped(evt);
            }
        });
        jPanel10.add(txtDiretorNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 470, 20));

        jLabelDiretorData.setText("Data:");
        jLabelDiretorData.setAlignmentX(1.0F);
        jPanel10.add(jLabelDiretorData, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 40, 20));

        txtDiretorData.setBackground(java.awt.SystemColor.activeCaptionBorder);
        try {
            txtDiretorData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDiretorData.setEnabled(false);
        txtDiretorData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiretorDataActionPerformed(evt);
            }
        });
        jPanel10.add(txtDiretorData, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 100, -1));

        cbbPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel10.add(cbbPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 180, -1));

        jLabelDiretorPais.setText("Pais");
        jLabelDiretorPais.setAlignmentX(1.0F);
        jPanel10.add(jLabelDiretorPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 40, 20));

        jLabel1.setText("AAAA/MM/dd");
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        PainelGenero.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 630, 140));

        btnNovoDiretor.setText("Novo");
        btnNovoDiretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoDiretorActionPerformed(evt);
            }
        });
        PainelGenero.add(btnNovoDiretor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 70, -1));

        btnSalvarDiretor.setText("Salvar");
        btnSalvarDiretor.setActionCommand("btnAlterar");
        btnSalvarDiretor.setPreferredSize(new java.awt.Dimension(90, 29));
        btnSalvarDiretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarDiretorActionPerformed(evt);
            }
        });
        PainelGenero.add(btnSalvarDiretor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 100, 30));

        btnRemoverDiretor.setText("Remover");
        btnRemoverDiretor.setActionCommand("btnRemover");
        btnRemoverDiretor.setEnabled(false);
        btnRemoverDiretor.setPreferredSize(new java.awt.Dimension(90, 29));
        btnRemoverDiretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverDiretorActionPerformed(evt);
            }
        });
        PainelGenero.add(btnRemoverDiretor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 100, 30));

        btnCancelarDiretor.setText("Cancelar");
        btnCancelarDiretor.setActionCommand("btnImprimir");
        btnCancelarDiretor.setEnabled(false);
        btnCancelarDiretor.setPreferredSize(new java.awt.Dimension(90, 29));
        btnCancelarDiretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarDiretorActionPerformed(evt);
            }
        });
        PainelGenero.add(btnCancelarDiretor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 100, 30));

        btnFecharDiretor.setText("Fechar");
        btnFecharDiretor.setActionCommand("btnFechar");
        btnFecharDiretor.setPreferredSize(new java.awt.Dimension(90, 29));
        btnFecharDiretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharDiretorActionPerformed(evt);
            }
        });
        PainelGenero.add(btnFecharDiretor, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 100, 30));

        JTableDiretor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTableDiretor.setName(""); // NOI18N
        jScrollPane1.setViewportView(JTableDiretor);

        PainelGenero.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 610, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PainelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PainelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarDiretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarDiretorActionPerformed
        //Date enteredDate = (Date)dateField.getValue(); pegandod valores de um formatted text field data com simple date format
        
         if (txtDiretorData.getText().length()<7){ // Evita que um valor '' seja inserido no banco
                        
                        JOptionPane.showMessageDialog(null,"Data invalida!");
                        
                    } else {
             
             
              if (txtDiretorNome.getText().length()<1){ 
                        
                        JOptionPane.showMessageDialog(null,"Nome vazio!");
              } else {        
                        
                        //enableButtons(false, true, true, true);

            int dialogResult = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja salvar esse registro?", "Confirmação?", JOptionPane.YES_NO_OPTION);


                if (dialogResult == JOptionPane.YES_OPTION) {
                    try {
                        if (addRecord == true) {
                            addNew();

                        } else {


                            updateRecord();
                        }
                        addRecord = false;

                        txtDiretorNome.setEnabled(false);
                        txtDiretorData.setEnabled(false);

                        txtDiretorNome.setBackground(Color.gray);
                        txtDiretorData.setBackground(Color.gray);

                        enableButtons(true, false, false, false);
                        clearInputBoxes();
                        enableFields(false);

                        loadRecords();

                    } catch (IOException | ClassNotFoundException | SQLException ex) {
                        System.out.println(ex.getMessage());
                   
                }
            }
        }
         }
    
    }//GEN-LAST:event_btnSalvarDiretorActionPerformed

 
    private void btnRemoverDiretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverDiretorActionPerformed
        if (!txtDiretorData.getText().isEmpty()) {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja excluir esse registro?", "Confirmação?", JOptionPane.YES_NO_OPTION);

            if (dialogResult == JOptionPane.YES_OPTION) {
                try {
                    deleteRecord();
                    loadRecords();
                    clearInputBoxes();
                    enableButtons(true, false, false, false);
                    
                    txtDiretorData.setEnabled(false);
                    txtDiretorData.setBackground(Color.gray);
                    
                    txtDiretorNome.setEnabled(false);
                    txtDiretorNome.setBackground(Color.gray);
                    
                    //cbbPais.setEnabled(false);
                    //cbbPais.setBackground(Color.gray);
                    
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnRemoverDiretorActionPerformed

    private void btnCancelarDiretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarDiretorActionPerformed
        clearInputBoxes();
        enableButtons(true, false, false, false);
        addRecord = false;
        
        txtDiretorNome.setEnabled(false);
        txtDiretorData.setEnabled(false);
        
        txtDiretorNome.setBackground(Color.gray);
        txtDiretorData.setBackground(Color.gray);
    }//GEN-LAST:event_btnCancelarDiretorActionPerformed

    private void btnFecharDiretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharDiretorActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharDiretorActionPerformed

    private void btnNovoDiretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoDiretorActionPerformed
        addRecord = true;
    
        clearInputBoxes();
        
        /*if (txtGeneroNome.getText().length()<1 ){ // Evita que um valor '' seja inserido no banco
                        enableButtons(false, true, true, false);  
                    } else {
                        enableButtons(false, true, true, true);
                    }
        */ // não é aaqui
                    
        
        txtDiretorNome.setEnabled(true);
        txtDiretorData.setEnabled(true);
        cbbPais.setEnabled(true);
        
        txtDiretorNome.setBackground(Color.white);
        txtDiretorData.setBackground(Color.white);
        cbbPais.setBackground(Color.white);
        
        enableButtons(false, true, true, false);
        
        txtDiretorNome.requestFocus();
    }//GEN-LAST:event_btnNovoDiretorActionPerformed

    private void txtDiretorNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiretorNomeKeyTyped
       if (txtDiretorNome.getText().length() >= 100 ) // limit textfield to 3 characters
            evt.consume();  
    }//GEN-LAST:event_txtDiretorNomeKeyTyped

    private void txtDiretorDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiretorDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiretorDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiretorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiretorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiretorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiretorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiretorDialog dialog = new DiretorDialog();//new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    boolean addRecord = false;

    private void clearInputBoxes() {
        txtDiretorData.setText("");
        txtDiretorNome.setText("");
       
    }
    
    private void addNew() throws SQLException, ClassNotFoundException, IOException{
       
        PaisDAO paisDAO = new PaisDAO();
        
        Diretor a= new Diretor();
        DiretorDAO diretorDAO = new DiretorDAO();
        
        a.setNome(txtDiretorNome.getText());
        
        Date data = null;
        String sData= txtDiretorData.getText();
        try {
        data = formatter.parse(sData);
               
        }catch (ParseException e) {    
        }
                
        a.setDataNasc(data);    
        a.setPais(paisDAO.find((String) cbbPais.getSelectedItem()));
        
        diretorDAO.insert(a);
    }

    private void updateRecord() throws SQLException {
        Diretor a = new Diretor();
        //Pais p = new Pais();
        PaisDAO paisDAO = new PaisDAO();
        
        
        
        Date data = null;
        String sData= txtDiretorData.getText();
        try {
        data = formatter.parse(sData);
               
        }catch (ParseException e) {    
        }
        
        a.setNome(txtDiretorNome.getText());        
        a.setDataNasc(data);
        a.setPais(paisDAO.find((String)cbbPais.getSelectedItem()));
        
        //Object id = JTableDiretor.getValueAt(JTableDiretor.getSelectedRow(), 0);
        DiretorDAO diretorDAO = new DiretorDAO();
        diretorDAO.update(a);//(p,id.toString());
    }

    private void deleteRecord() throws SQLException {
        DiretorDAO diretorDAO = new DiretorDAO();
        diretorDAO.remove(txtDiretorNome.getText());
    }
    
    private void loadRecords() throws SQLException {
        
        String sql = "SELECT A.NomeDiretor as Nome, A.DataNascimento as 'Nascido em ', A.Pais_Sigla as 'Sigla do Pais' FROM Filme.Diretor as A , Filme.Pais as P WHERE A.Pais_Sigla = P.Sigla;";
        ResultSetTableModel tableModel = new ResultSetTableModel(sql);
        JTableDiretor.setModel(tableModel);
        
          //Hiding column "id" and equipe_id 
        //JTableDiretor.removeColumn(JTableDiretor.getColumnModel().getColumn(0));
        //JTableDiretor.removeColumn(JTableDiretor.getColumnModel().getColumn(1));
        
         //Adjusting columns 
        JTableDiretor.getColumnModel().getColumn(0).setMinWidth(120);//"Nome
        JTableDiretor.getColumnModel().getColumn(1).setMinWidth(200);//"Nascido em
        JTableDiretor.getColumnModel().getColumn(2).setMaxWidth(50); //"Sigla do pais"
        //JTableDiretor.getColumnModel().getColumn(3).setMaxWidth(40); //"status"
       
        JTableDiretor.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                try {
                    if (JTableDiretor.getSelectedRow() >= 0) {
                        Object nome = JTableDiretor.getModel().getValueAt(JTableDiretor.getSelectedRow(), 0);
                        Object dataNasc = JTableDiretor.getModel().getValueAt(JTableDiretor.getSelectedRow(), 1);
                        //Object equipe_id = JTableDiretor.getModel().getValueAt(JTableDiretor.getSelectedRow(), 2);
                        Object pais_sigla = JTableDiretor.getModel().getValueAt(JTableDiretor.getSelectedRow(), 2);
                        //Object status = JTableDiretor.getModel().getValueAt(JTableDiretor.getSelectedRow(), 5).toString();
                        //String data= nome.toString();
                        //String teste=data.replace(0, 0);
                        txtDiretorNome.setText(nome.toString());
                        txtDiretorData.setText(dataNasc.toString().replace('-','/'));
                        //txtDiretorData.setText("1111/11/11");
                        cbbPais.setSelectedItem(pais_sigla.toString());
                        
                        //EquipeDAO eDao = new EquipeDAO();
                        //Equipe e = eDao.find(Integer.parseInt(equipe_id.toString()));
                        //txtEquipeNome.setText(e.getNome());             
                        
                        //CBStatus.setSelected(status.equals("true"));
                        
                        enableButtons(false, true, true, true);
                        enableFields(true);
                    }
                } catch (NumberFormatException ex) {
                    //                } catch (IOException | ClassNotFoundException | NumberFormatException | SQLException ex) {

                    System.out.println(ex.getMessage());
                }
            }
        });

        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.LEFT);
        JTableDiretor.getColumnModel().getColumn(0).setCellRenderer(rightRenderer);
    }
    
    
    private void fillCBBPais() throws SQLException {
        PaisDAO dao = new PaisDAO();
        List<Pais> paises = dao.list();
        cbbPais.removeAllItems();
        for(Pais p : paises){
            cbbPais.addItem(p.getSigla());
        }        
    }
    
     public void enableButtons(boolean novo, boolean salvar, boolean cancelar, boolean remover){
        btnNovoDiretor.setEnabled(novo);
        btnSalvarDiretor.setEnabled(salvar);
        btnCancelarDiretor.setEnabled(cancelar);
        btnRemoverDiretor.setEnabled(remover);
    
     }
     
     private void enableFields(boolean flag) {
        cbbPais.setEnabled(flag);
        txtDiretorData.setEnabled(flag);
        txtDiretorNome.setEnabled(flag);
        //btnBuscaEquipe.setEnabled(flag);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableDiretor;
    private javax.swing.JPanel PainelGenero;
    private javax.swing.JButton btnCancelarDiretor;
    private javax.swing.JButton btnFecharDiretor;
    private javax.swing.JButton btnNovoDiretor;
    private javax.swing.JButton btnRemoverDiretor;
    private javax.swing.JButton btnSalvarDiretor;
    private javax.swing.JComboBox<String> cbbPais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDiretorData;
    private javax.swing.JLabel jLabelDiretorNome;
    private javax.swing.JLabel jLabelDiretorPais;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField txtDiretorData;
    private java.awt.TextField txtDiretorNome;
    // End of variables declaration//GEN-END:variables
}
