/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.DiretorDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableCellRenderer;
import MODEL.Pais;
import MODEL.Filme;
import DAO.PaisDAO;
import DAO.FilmeDAO;
import DAO.ProdutoraDAO;
import MODEL.Diretor;
import MODEL.Produtora;
import java.awt.Color;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author alan
 */
public class FilmeDialog extends javax.swing.JDialog {
    //SimpleDateFormat formatter = new SimpleDateFormat("yyyy/MM/dd");

    /**
     * Creates new form NewJDialog
     */
    /*public GeneroDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
     try {
            loadRecords();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }
    */
    
    public FilmeDialog() throws ClassNotFoundException, IOException {
        //super(modal);
     initComponents();
     try {
            loadRecords();
            fillCBBProdutora();
            fillCBBDiretor();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelGenero = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabelFilmeNome = new javax.swing.JLabel();
        txtFilmeNome = new java.awt.TextField();
        jLabelFilmeAno = new javax.swing.JLabel();
        cbbProdutora = new javax.swing.JComboBox<>();
        jLabelFilmeProdutora = new javax.swing.JLabel();
        txtFilmeAno = new java.awt.TextField();
        jLabelFilmeDiretor = new javax.swing.JLabel();
        cbbDiretor = new javax.swing.JComboBox<>();
        btnGeneros = new javax.swing.JButton();
        btnNovoFilme = new javax.swing.JButton();
        btnSalvarFilme = new javax.swing.JButton();
        btnRemoverFilme = new javax.swing.JButton();
        btnCancelarFilme = new javax.swing.JButton();
        btnFecharFilme = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableFilme = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PainelGenero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(254, 254, 254));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "REGISTRO DE ATORES"));
        jPanel10.setToolTipText("");
        jPanel10.setAlignmentX(0.2F);
        jPanel10.setAlignmentY(0.7F);
        jPanel10.setName("Pais_Tab_Panel"); // NOI18N
        jPanel10.setRequestFocusEnabled(false);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFilmeNome.setText("Nome:");
        jLabelFilmeNome.setAlignmentX(1.0F);
        jPanel10.add(jLabelFilmeNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 20));

        txtFilmeNome.setBackground(java.awt.SystemColor.activeCaptionBorder);
        txtFilmeNome.setEnabled(false);
        txtFilmeNome.setName("txtNome"); // NOI18N
        txtFilmeNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFilmeNomeKeyTyped(evt);
            }
        });
        jPanel10.add(txtFilmeNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 190, 20));

        jLabelFilmeAno.setText("Ano:");
        jLabelFilmeAno.setAlignmentX(1.0F);
        jPanel10.add(jLabelFilmeAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 40, 20));

        cbbProdutora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel10.add(cbbProdutora, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 180, -1));

        jLabelFilmeProdutora.setText("Produtora");
        jLabelFilmeProdutora.setAlignmentX(1.0F);
        jPanel10.add(jLabelFilmeProdutora, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 80, 20));

        txtFilmeAno.setBackground(java.awt.SystemColor.activeCaptionBorder);
        txtFilmeAno.setEnabled(false);
        txtFilmeAno.setName("txtNome"); // NOI18N
        txtFilmeAno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFilmeAnoKeyTyped(evt);
            }
        });
        jPanel10.add(txtFilmeAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 190, 20));

        jLabelFilmeDiretor.setText("Diretor");
        jLabelFilmeDiretor.setAlignmentX(1.0F);
        jPanel10.add(jLabelFilmeDiretor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 70, 20));

        cbbDiretor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel10.add(cbbDiretor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 180, -1));

        btnGeneros.setText("Generos");
        btnGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerosActionPerformed(evt);
            }
        });
        jPanel10.add(btnGeneros, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        PainelGenero.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 630, 140));

        btnNovoFilme.setText("Novo");
        btnNovoFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoFilmeActionPerformed(evt);
            }
        });
        PainelGenero.add(btnNovoFilme, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 70, -1));

        btnSalvarFilme.setText("Salvar");
        btnSalvarFilme.setActionCommand("btnAlterar");
        btnSalvarFilme.setPreferredSize(new java.awt.Dimension(90, 29));
        btnSalvarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarFilmeActionPerformed(evt);
            }
        });
        PainelGenero.add(btnSalvarFilme, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 100, 30));

        btnRemoverFilme.setText("Remover");
        btnRemoverFilme.setActionCommand("btnRemover");
        btnRemoverFilme.setEnabled(false);
        btnRemoverFilme.setPreferredSize(new java.awt.Dimension(90, 29));
        btnRemoverFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverFilmeActionPerformed(evt);
            }
        });
        PainelGenero.add(btnRemoverFilme, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 100, 30));

        btnCancelarFilme.setText("Cancelar");
        btnCancelarFilme.setActionCommand("btnImprimir");
        btnCancelarFilme.setEnabled(false);
        btnCancelarFilme.setPreferredSize(new java.awt.Dimension(90, 29));
        btnCancelarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarFilmeActionPerformed(evt);
            }
        });
        PainelGenero.add(btnCancelarFilme, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 100, 30));

        btnFecharFilme.setText("Fechar");
        btnFecharFilme.setActionCommand("btnFechar");
        btnFecharFilme.setPreferredSize(new java.awt.Dimension(90, 29));
        btnFecharFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharFilmeActionPerformed(evt);
            }
        });
        PainelGenero.add(btnFecharFilme, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 100, 30));

        JTableFilme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTableFilme.setName(""); // NOI18N
        jScrollPane1.setViewportView(JTableFilme);

        PainelGenero.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 610, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PainelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PainelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarFilmeActionPerformed
        //Date enteredDate = (Date)dateField.getValue(); pegandod valores de um formatted text field data com simple date format
        
         if (txtFilmeAno.getText().length()<4){ // Evita que um valor '' seja inserido no banco
                        
                        JOptionPane.showMessageDialog(null,"Data invalida!");
                        
                    } else {
             
             
              if (txtFilmeNome.getText().length()<1){ 
                        
                        JOptionPane.showMessageDialog(null,"Nome vazio!");
              } else {        
                        
                        //enableButtons(false, true, true, true);

            int dialogResult = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja salvar esse registro?", "Confirmação?", JOptionPane.YES_NO_OPTION);


                if (dialogResult == JOptionPane.YES_OPTION) {
                    try {
                        if (addRecord == true) {
                            addNew();

                        } else {


                            updateRecord();
                        }
                        addRecord = false;

                        txtFilmeNome.setEnabled(false);
                        txtFilmeAno.setEnabled(false);

                        txtFilmeNome.setBackground(Color.gray);
                        txtFilmeAno.setBackground(Color.gray);

                        enableButtons(true, false, false, false);
                        clearInputBoxes();
                        enableFields(false);

                        loadRecords();

                    } catch (IOException | ClassNotFoundException | SQLException ex) {
                        System.out.println(ex.getMessage());
                   
                }
            }
        }
         }
    
    }//GEN-LAST:event_btnSalvarFilmeActionPerformed

 
    private void btnRemoverFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverFilmeActionPerformed
        if (!txtFilmeAno.getText().isEmpty()) {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja excluir esse registro?", "Confirmação?", JOptionPane.YES_NO_OPTION);

            if (dialogResult == JOptionPane.YES_OPTION) {
                try {
                    deleteRecord();
                    loadRecords();
                    clearInputBoxes();
                    enableButtons(true, false, false, false);
                    
                    txtFilmeAno.setEnabled(false);
                    txtFilmeAno.setBackground(Color.gray);
                    
                    txtFilmeNome.setEnabled(false);
                    txtFilmeNome.setBackground(Color.gray);
                    
                    //cbbPais.setEnabled(false);
                    //cbbPais.setBackground(Color.gray);
                    
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnRemoverFilmeActionPerformed

    private void btnCancelarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarFilmeActionPerformed
        clearInputBoxes();
        enableButtons(true, false, false, false);
        addRecord = false;
        
        txtFilmeNome.setEnabled(false);
        txtFilmeAno.setEnabled(false);
        
        txtFilmeNome.setBackground(Color.gray);
        txtFilmeAno.setBackground(Color.gray);
    }//GEN-LAST:event_btnCancelarFilmeActionPerformed

    private void btnFecharFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharFilmeActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharFilmeActionPerformed

    private void btnNovoFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoFilmeActionPerformed
        addRecord = true;
    
        clearInputBoxes();
        
        /*if (txtGeneroNome.getText().length()<1 ){ // Evita que um valor '' seja inserido no banco
                        enableButtons(false, true, true, false);  
                    } else {
                        enableButtons(false, true, true, true);
                    }
        */ // não é aaqui
                    
        
        txtFilmeNome.setEnabled(true);
        txtFilmeAno.setEnabled(true);
        cbbProdutora.setEnabled(true);
        
        txtFilmeNome.setBackground(Color.white);
        txtFilmeAno.setBackground(Color.white);
        cbbProdutora.setBackground(Color.white);
        
        enableButtons(false, true, true, false);
        
        txtFilmeNome.requestFocus();
    }//GEN-LAST:event_btnNovoFilmeActionPerformed

    private void txtFilmeNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilmeNomeKeyTyped
       if (txtFilmeNome.getText().length() >= 200 ) // limit textfield to 3 characters
            evt.consume();  
    }//GEN-LAST:event_txtFilmeNomeKeyTyped

    private void txtFilmeAnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilmeAnoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilmeAnoKeyTyped

    private void btnGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerosActionPerformed
        String id=txtFilmeNome.getText();
                //"Teste";
     
     
        Genero_FilmeDialog g = new Genero_FilmeDialog(id);
       
        g.setVisible(true);
     
    }//GEN-LAST:event_btnGenerosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilmeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilmeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilmeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilmeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FilmeDialog dialog = null;
                try {
                    dialog = new FilmeDialog(); //new javax.swing.JFrame(), true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FilmeDialog.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(FilmeDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    boolean addRecord = false;

    private void clearInputBoxes() {
        txtFilmeAno.setText("");
        txtFilmeNome.setText("");
       
    }
    
    private void addNew() throws SQLException, ClassNotFoundException, IOException{
       
        PaisDAO paisDAO = new PaisDAO();
        
        DiretorDAO diretorDAO = new DiretorDAO();
        
        ProdutoraDAO produtoraDAO = new ProdutoraDAO();
        
        Filme f= new Filme();
        FilmeDAO filmeDAO = new FilmeDAO();
        
        f.setNome(txtFilmeNome.getText());
        
        f.setAno(Integer.parseInt(txtFilmeAno.getText()));
       
        f.setProdutora(produtoraDAO.find((String)cbbProdutora.getSelectedItem()));
        f.setDiretor(diretorDAO.find((String)cbbDiretor.getSelectedItem()));
        
        filmeDAO.insert(f);
    }

    private void updateRecord() throws SQLException, ClassNotFoundException, IOException {
        Filme f = new Filme();
        DiretorDAO diretorDAO = new DiretorDAO();
        ProdutoraDAO produtoraDAO = new ProdutoraDAO();
        
        FilmeDAO filmeDAO = new FilmeDAO();
        
        
        
        
        
        f.setNome(txtFilmeNome.getText());
        
        f.setAno(Integer.parseInt(txtFilmeAno.getText()));
       
        f.setProdutora(produtoraDAO.find((String)cbbProdutora.getSelectedItem()));
        f.setDiretor(diretorDAO.find((String)cbbDiretor.getSelectedItem()));
        
        filmeDAO.update(f);
        
    }

    private void deleteRecord() throws SQLException {
        FilmeDAO filmeDAO = new FilmeDAO();
        filmeDAO.remove(txtFilmeNome.getText());
    }
    
    private void loadRecords() throws SQLException {
        
        String sql = "SELECT A.Nome as 'Nome', A.Produtora_idNomeProdutora as 'Produtora', A.Diretor_NomeDiretor as 'Nome Diretor', A.Ano as 'ano' FROM Filme.Filme as A;";
        ResultSetTableModel tableModel = new ResultSetTableModel(sql);
        JTableFilme.setModel(tableModel);
        
          //Hiding column "id" and equipe_id 
        //JTableFilme.removeColumn(JTableFilme.getColumnModel().getColumn(0));
        //JTableFilme.removeColumn(JTableFilme.getColumnModel().getColumn(1));
        
         //Adjusting columns 
        JTableFilme.getColumnModel().getColumn(0).setMinWidth(120);//"Nome
        JTableFilme.getColumnModel().getColumn(1).setMinWidth(50);//"Produtora
        JTableFilme.getColumnModel().getColumn(2).setMaxWidth(50); //"Diretor"
        JTableFilme.getColumnModel().getColumn(3).setMaxWidth(40); //"Ano"
       
        JTableFilme.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                try {
                    if (JTableFilme.getSelectedRow() >= 0) {
                        Object nome = JTableFilme.getModel().getValueAt(JTableFilme.getSelectedRow(), 0);
                        Object prod = JTableFilme.getModel().getValueAt(JTableFilme.getSelectedRow(), 1);
                        //Object equipe_id = JTableFilme.getModel().getValueAt(JTableFilme.getSelectedRow(), 2);
                        Object direc = JTableFilme.getModel().getValueAt(JTableFilme.getSelectedRow(), 2);
                        Object ano = JTableFilme.getModel().getValueAt(JTableFilme.getSelectedRow(), 3).toString();
                        //nt ano = nome.toString();
                        //String teste=data.replace(0, 0);
                        txtFilmeNome.setText(nome.toString());
                        txtFilmeAno.setText(ano.toString());
                        //txtFilmeAno.setText("1111/11/11");
                        cbbProdutora.setSelectedItem(prod.toString());
                        cbbDiretor.setSelectedItem(direc.toString());
                        
                        //EquipeDAO eDao = new EquipeDAO();
                        //Equipe e = eDao.find(Integer.parseInt(equipe_id.toString()));
                        //txtEquipeNome.setText(e.getNome());             
                        
                        //CBStatus.setSelected(status.equals("true"));
                        
                        enableButtons(false, true, true, true);
                        enableFields(true);
                    }
                } catch (NumberFormatException ex) {
                    //                } catch (IOException | ClassNotFoundException | NumberFormatException | SQLException ex) {

                    System.out.println(ex.getMessage());
                }
            }
        });

        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.LEFT);
        JTableFilme.getColumnModel().getColumn(0).setCellRenderer(rightRenderer);
    }
    
    
    private void fillCBBProdutora() throws SQLException, ClassNotFoundException, IOException {
        ProdutoraDAO dao = new ProdutoraDAO();
        List<Produtora> produtoras = dao.list();
        cbbProdutora.removeAllItems();
        for(Produtora p : produtoras){
            cbbProdutora.addItem(p.getNome());
        }        
    }
    
     private void fillCBBDiretor() throws SQLException, ClassNotFoundException, IOException {
        DiretorDAO dao = new DiretorDAO();
        List<Diretor> diretores = dao.list();
        cbbDiretor.removeAllItems();
        for(Diretor d : diretores){
            cbbDiretor.addItem(d.getNome());
        }        
    }
    
     public void enableButtons(boolean novo, boolean salvar, boolean cancelar, boolean remover){
        btnNovoFilme.setEnabled(novo);
        btnSalvarFilme.setEnabled(salvar);
        btnCancelarFilme.setEnabled(cancelar);
        btnRemoverFilme.setEnabled(remover);
    
     }
     
     private void enableFields(boolean flag) {
        cbbProdutora.setEnabled(flag);
        txtFilmeAno.setEnabled(flag);
        txtFilmeNome.setEnabled(flag);
        //btnBuscaEquipe.setEnabled(flag);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableFilme;
    private javax.swing.JPanel PainelGenero;
    private javax.swing.JButton btnCancelarFilme;
    private javax.swing.JButton btnFecharFilme;
    private javax.swing.JButton btnGeneros;
    private javax.swing.JButton btnNovoFilme;
    private javax.swing.JButton btnRemoverFilme;
    private javax.swing.JButton btnSalvarFilme;
    private javax.swing.JComboBox<String> cbbDiretor;
    private javax.swing.JComboBox<String> cbbProdutora;
    private javax.swing.JLabel jLabelFilmeAno;
    private javax.swing.JLabel jLabelFilmeDiretor;
    private javax.swing.JLabel jLabelFilmeNome;
    private javax.swing.JLabel jLabelFilmeProdutora;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.TextField txtFilmeAno;
    private java.awt.TextField txtFilmeNome;
    // End of variables declaration//GEN-END:variables
}
