/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.FilmeDAO;
import DAO.Filme_GeneroDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableCellRenderer;
import MODEL.Genero;
import MODEL.Filme;
import DAO.GeneroDAO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.*;
import UI.PassaString;


/**
 *
 * @author alan
 */
public class Genero_FilmeDialog extends javax.swing.JDialog {
    String idGenero;
    DefaultListModel listaGenero=new DefaultListModel();
    
    static String idFilme;
    
    public  Genero_FilmeDialog(String teste) {
        Genero_FilmeDialog.idFilme=teste;
     
        //super(modal);
     
     initComponents();
     try {
            loadRecords();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
     
    //return idFilme;
    jTextField1.setText(idFilme);
    }

    
   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelGenero = new javax.swing.JPanel();
        btnAdicionarGenero = new javax.swing.JButton();
        btnFecharGenero = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTableGenero = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListGeneros = new javax.swing.JList<>();
        btnRemoverGenero = new javax.swing.JButton();
        btnSalvarGenero = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PainelGenero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdicionarGenero.setText(">>>>>>");
        btnAdicionarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarGeneroActionPerformed(evt);
            }
        });
        PainelGenero.add(btnAdicionarGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 70, -1));

        btnFecharGenero.setText("Fechar");
        btnFecharGenero.setActionCommand("btnFechar");
        btnFecharGenero.setPreferredSize(new java.awt.Dimension(90, 29));
        btnFecharGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharGeneroActionPerformed(evt);
            }
        });
        PainelGenero.add(btnFecharGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 100, 30));

        JTableGenero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTableGenero.setName(""); // NOI18N
        jScrollPane2.setViewportView(JTableGenero);

        PainelGenero.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 250));

        jListGeneros.setModel(listaGenero);
        jScrollPane3.setViewportView(jListGeneros);

        PainelGenero.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 150, 260));

        btnRemoverGenero.setText("<<<<<<");
        btnRemoverGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverGeneroActionPerformed(evt);
            }
        });
        PainelGenero.add(btnRemoverGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 70, -1));

        btnSalvarGenero.setText("Salvar e fechar");
        btnSalvarGenero.setActionCommand("btnFechar");
        btnSalvarGenero.setPreferredSize(new java.awt.Dimension(90, 29));
        btnSalvarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarGeneroActionPerformed(evt);
            }
        });
        PainelGenero.add(btnSalvarGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 130, 30));

        jTextField1.setText("jTextField1");
        PainelGenero.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PainelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PainelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
 
    private void btnFecharGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharGeneroActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharGeneroActionPerformed

    private void btnAdicionarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarGeneroActionPerformed
        addRecord = true;
        listaGenero.addElement(idGenero);
    
    }//GEN-LAST:event_btnAdicionarGeneroActionPerformed

    private void btnRemoverGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverGeneroActionPerformed
        // TODO add your handling code here:
        addRecord = true;
        listaGenero.removeElement(idGenero);
    }//GEN-LAST:event_btnRemoverGeneroActionPerformed

    private void btnSalvarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarGeneroActionPerformed
        // TODO add your handling code here:
        salvaGenero();
        this.dispose();
    }//GEN-LAST:event_btnSalvarGeneroActionPerformed
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Genero_FilmeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Genero_FilmeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Genero_FilmeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Genero_FilmeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Genero_FilmeDialog dialog = new Genero_FilmeDialog(idFilme);//new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    boolean addRecord = false;
    
    private void clearInputBoxes() {
        //txtGeneroNome.setText("");
        //txtGeneroDesc.setText("");
    }
    
    private void addNew() throws SQLException {
        Genero g = new Genero();
        //g.setIdGenero(txtGeneroNome.getText());
       // g.setDescricao(txtGeneroDesc.getText());
        GeneroDAO dao = new GeneroDAO();
        dao.insert(g);
    }

    private void updateRecord() throws SQLException {
        Genero g = new Genero();
        //g.setIdGenero(txtGeneroNome.getText());
        //g.setDescricao(txtGeneroDesc.getText());
        Object id = JTableGenero.getValueAt(JTableGenero.getSelectedRow(), 0);
        GeneroDAO dao = new GeneroDAO();
        dao.update(g,id.toString());
    }

    private void deleteRecord() throws SQLException {
        GeneroDAO dao = new GeneroDAO();
        
        //dao.remove(txtGeneroNome.getText());
    }
    
    public void salvaGenero() {
        
        List<String> l = jListGeneros.getSelectedValuesList();
        
        
        Filme_GeneroDAO filme_GeneroDAO = new Filme_GeneroDAO();
        
        
        System.out.println(idFilme);
       
        for ( String e : l ) {
            
            
            
            try {
                filme_GeneroDAO.insert(idFilme,e);
            } catch (SQLException ex) {
                Logger.getLogger(Genero_FilmeDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
      
    }
    
    private void loadRecords() throws SQLException {
        String sql = "SELECT idGenero FROM Filme.Genero ORDER BY idGenero";
        ResultSetTableModel tableModel = new ResultSetTableModel(sql);
        JTableGenero.setModel(tableModel);
        
        JTableGenero.getColumnModel().getColumn(0).setWidth(50);
        JTableGenero.getColumnModel().getColumn(0).setMinWidth(50);
        //JTableGenero.getColumnModel().getColumn(0).setMaxWidth(50);
        
        JTableGenero.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            try {
                if (JTableGenero.getSelectedRow() >= 0) {
                    Object nome = JTableGenero.getValueAt(JTableGenero.getSelectedRow(), 0);
                    //Object desc = JTableGenero.getValueAt(JTableGenero.getSelectedRow(), 1);
                    //Object d = JTableGenero.getValueAt(JTableGenero.getSelectedRow(), 2);

                    idGenero=(nome.toString());
                   // txtGeneroDesc.setText(desc.toString());
                    
                    
                    
                    //txtGeneroNome.setEnabled(true);
                   // txtGeneroDesc.setEnabled(true);//teste
                    
                   // txtGeneroDesc.setBackground(Color.white);
                   // txtGeneroNome.setBackground(Color.white);// teste
                    
                    //enableButtons(false, true, true, true);
                }
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        });
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.LEFT);
        JTableGenero.getColumnModel().getColumn(0).setCellRenderer(rightRenderer);
    }
    
     /*public void enableButtons(boolean novo, boolean salvar, boolean cancelar, boolean remover){
        btnAdicionarGenero.setEnabled(novo);
        //btnSalvarGenero.setEnabled(salvar);
        btnCancelarGenero.setEnabled(cancelar);
        btnRemoverGenero.setEnabled(remover);
    
     }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable JTableGenero;
    public javax.swing.JPanel PainelGenero;
    public javax.swing.JButton btnAdicionarGenero;
    public javax.swing.JButton btnFecharGenero;
    public javax.swing.JButton btnRemoverGenero;
    javax.swing.JButton btnSalvarGenero;
    public javax.swing.JList<String> jListGeneros;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
